-- Auto-generated by Migra on python.exe at F:\work\flyway-project1
create sequence "public"."categories_id_seq";

create table "public"."categories" (
    "id" integer not null default nextval('categories_id_seq'::regclass),
    "name" character varying(100) not null,
    "created_at" timestamp with time zone default now()
);


alter sequence "public"."categories_id_seq" owned by "public"."categories"."id";

CREATE UNIQUE INDEX categories_name_key ON public.categories USING btree (name);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."categories" add constraint "categories_name_key" UNIQUE using index "categories_name_key";
-- DDL synchronization complete.